In [1798]:
import pandas as pd
import numpy as np

df=pd.read_excel('movie_dataSet_2023.xlsx')
print(df)

                           movie   language               director  Action  \
0                          Jawan      Hindi                  Atlee       1   
1                        Pathaan      Hindi        Siddharth Anand       1   
2                         Animal      Hindi    Sandeep Reddy Vanga       1   
3                        Gadar 2      Hindi            Anil Sharma       1   
4    Salaar: Cease Fire - Part 1     Telugu         Prashanth Neel       1   
..                           ...        ...                    ...     ...   
133                    Runway 34      Hindi             Ajay Devgn       0   
134    Vendhu Thanindhathu Kaadu      Tamil  Gautham Vasudev Menon       1   
135                 Malikappuram  Malayalam    Vishnu Sasi Shankar       1   
136   Rocketry: The Nambi Effect      Tamil               Madhavan       0   
137               Jana Gana Mana  Malayalam       Dijo Jose Antony       0   

     Drama  Musical  Adventure  Thriller  Crime  Comedy  ...  A

In [1799]:
x=df.iloc[:,1:27].values
y=df.iloc[:,-1].values



In [1800]:

print(x)



[['Hindi' 'Atlee' 1 ... 285 169 129.6]
 ['Hindi' 'Siddharth Anand' 1 ... 250 146 104.8]
 ['Hindi' 'Sandeep Reddy Vanga' 1 ... 140 204 115.9]
 ...
 ['Malayalam' 'Vishnu Sasi Shankar' 1 ... 10 121 36.1]
 ['Tamil' 'Madhavan' 0 ... 50 157 35.7]
 ['Malayalam' 'Dijo Jose Antony' 0 ... 15 162 27.1]]


In [1801]:
print(y)

['Hit' 'Hit' 'Hit' 'Hit' 'Hit' 'Hit' 'Hit' 'Hit' 'Flop' 'Flop' 'Hit' 'Hit'
 'Hit' 'Hit' 'Hit' 'Hit' 'Hit' 'Hit' 'Flop' 'Hit' 'Hit' 'Hit' 'Hit' 'Hit'
 'Hit' 'Hit' 'Hit' 'Hit' 'Flop' 'Hit' 'Flop' 'Hit' 'Hit' 'Flop' 'Hit'
 'Hit' 'Hit' 'Hit' 'Hit' 'Hit' 'Hit' 'Hit' 'Flop' 'Hit' 'Flop' 'Hit' 'Hit'
 'Hit' 'Hit' 'Hit' 'Flop' 'Hit' 'Flop' 'Hit' 'Hit' 'Hit' 'Hit' 'Hit'
 'Flop' 'Hit' 'Flop' 'Hit' 'Hit' 'Flop' 'Flop' 'Flop' 'Hit' 'Hit' 'Flop'
 'Flop' 'Flop' 'Hit' 'Hit' 'Hit' 'Hit' 'Flop' 'Flop' 'Hit' 'Hit' 'Flop'
 'Hit' 'Flop' 'Hit' 'Hit' 'Hit' 'Hit' 'Hit' 'Hit' 'Flop' 'Hit' 'Hit' 'Hit'
 'Hit' 'Hit' 'Flop' 'Hit' 'Flop' 'Flop' 'Flop' 'Flop' 'Flop' 'Flop' 'Flop'
 'Hit' 'Hit' 'Hit' 'Flop' 'Flop' 'Flop' 'Flop' 'Hit' 'Hit' 'Hit' 'Hit'
 'Flop' 'Hit' 'Flop' 'Flop' 'Flop' 'Hit' 'Flop' 'Hit' 'Flop' 'Hit' 'Flop'
 'Flop' 'Flop' 'Hit' 'Hit' 'Flop' 'Hit' 'Hit' 'Hit' 'Flop' 'Hit' 'Hit'
 'Flop' 'Hit']


In [1802]:
# from sklearn.preprocessing import OneHotEncoder, LabelEncoder
# from sklearn.compose import ColumnTransformer

# # Assuming these are the column indices you want to encode
# columns_to_encode = [0, 1]

# # Preprocess non-numeric columns with LabelEncoder
# label_encoders = {}
# for col in columns_to_encode:
#     label_encoders[col] = LabelEncoder()
#     x[:, col] = label_encoders[col].fit_transform(x[:, col])

# # Apply ColumnTransformer with OneHotEncoder
# ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), columns_to_encode)], remainder='passthrough')

# x = ct.fit_transform(x)


In [1803]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

x[:,0]=le.fit_transform(x[:,0])
x[:,1]=le.fit_transform(x[:,1])
x[:,19]=le.fit_transform(x[:,19])
x[:,20]=le.fit_transform(x[:,20])
x[:,21]=le.fit_transform(x[:,21])
x[:,22]=le.fit_transform(x[:,22])


In [1804]:
y = le.fit_transform(y)

In [1805]:
print(x)

[[1 18 1 ... 285 169 129.6]
 [1 108 1 ... 250 146 104.8]
 [1 102 1 ... 140 204 115.9]
 ...
 [3 127 1 ... 10 121 36.1]
 [6 60 0 ... 50 157 35.7]
 [3 28 0 ... 15 162 27.1]]


In [1806]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.4,random_state=10)

In [1807]:
# from sklearn.decomposition import PCA


# pca  = PCA(n_components=1)
# x_train = pca.fit_transform(x_train)
# x_test = pca.transform(x_test)

In [1808]:
from cmath import inf
from sklearn import svm
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier

from sklearn.linear_model import LinearRegression

# dt=KNeighborsClassifier(n_neighbors=5,metric='correlation',p=inf)
# dt = DecisionTreeClassifier(criterion='gini',random_state=0)
# dt = svm.SVC(kernel='rbf',random_state=42)
# dt = LinearRegression()
# dt = RandomForestClassifier(n_estimators=5,criterion='gini',random_state=0)


# InvalidParameterError: The 'metric' parameter of pairwise_distances_chunked must be a str among {'cityblock', 'jaccard', 'precomputed', 'yule', 'chebyshev', 'wminkowski', 'correlation', 'minkowski', 'euclidean', 'sokalsneath', 'nan_euclidean', 'cosine', 'hamming', 'l1', 'canberra', 'seuclidean', 'russellrao', 'manhattan', 'matching', 'l2', 'sokalmichener', 'sqeuclidean', 'braycurtis', 'haversine', 'rogerstanimoto', 'dice', 'mahalanobis'} or a callable. Got 'pyfunc' instead.


#K-NN metics
#{'haversine', 'correlation', 'manhattan', 'braycurtis', 'chebyshev', 'precomputed', 'rogerstanimoto', 'nan_euclidean', 'sqeuclidean', 'cityblock', 'l2', 'infinity', 'dice', 'p', 'euclidean', 'seuclidean', 'sokalsneath', 'jaccard', 'minkowski', 'mahalanobis', 'yule', 'sokalmichener', 'pyfunc', 'cosine', 'hamming', 'l1', 'russellrao', 'canberra'}


In [1809]:
def weighted_distances(distances):
    return 1 / (distances + 0.001)  # Adding a small constant to avoid division by zero

# Initialize KNeighborsClassifier with weighted distances
dt = KNeighborsClassifier(n_neighbors=5, metric='correlation')

In [1810]:
# .0

In [1811]:
dt.fit(x_train,y_train)
y_pred=dt.predict(x_test)


In [1812]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix,precision_score
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(precision_score(y_test,y_pred, average='binary'))

0.8214285714285714
[[13  4]
 [ 6 33]]
              precision    recall  f1-score   support

           0       0.68      0.76      0.72        17
           1       0.89      0.85      0.87        39

    accuracy                           0.82        56
   macro avg       0.79      0.81      0.80        56
weighted avg       0.83      0.82      0.82        56

0.8918918918918919
